@startuml
left to right direction

actor User

rectangle JA {
    usecase Database
    usecase Scheduler
    usecase Dispatcher

    User --> Database
    Database --> Scheduler
    Scheduler --> Dispatcher

    rectangle ComputationalCluster {
        usecase Worker1
        usecase Worker2
        Dispatcher --> Worker1
        Dispatcher --> Worker2
    }
}

@enduml
