@startuml

box "Local components"
    boundary Boundary
    participant "command:Command" as Command
    participant ":SingleMessageProxy" as Proxy
    participant ":SSHConnection" as SSHConnection
    participant "response:Response" as Response
end box
participant ":Remote" as Remote

Boundary -> Proxy ++ : command
Proxy -> SSHConnection ** : Create
Proxy -> SSHConnection ++ : command
SSHConnection --> Remote ** : Call via SSH
activate Remote
Remote -> Remote : Read from stdin
SSHConnection --> Remote : Write command.serialize() on stdin
SSHConnection -> Remote : Read from stdout
... Remote processes command ...
Remote --> Remote : Write response as \nYAML to stdout
SSHConnection -> Response ** : Create
destroy Remote
Proxy <-- SSHConnection -- : response
Proxy -> SSHConnection !! : Close
Boundary <-- Proxy -- : response

destroy Response

@enduml
