@startuml

'This file is the same as proxy-one-message.puml except the SSHConnection is continuous 
'instead of created/destroyed for each Message.

box "Local components"
    boundary Boundary
    participant CommandMessage
    participant ContinuousProxy as Proxy
    participant SSHConnection
    participant ResponseMessage
end box

Boundary -> Proxy ++ : CommandMessage
'Proxy -> SSHConnection ** : Create
Proxy -> SSHConnection ++ : CommandMessage
SSHConnection -> Remote ** : Call via shell, YAML as argument
activate Remote
Remote -> Remote : Execute command
SSHConnection <- Remote -- : ResponseMessage as YAML
destroy Remote
SSHConnection -> ResponseMessage ** : Create
Proxy <- SSHConnection -- : ResponseMessage
'Proxy -> SSHConnection !!
Boundary <- Proxy -- : ResponseMessage

destroy ResponseMessage

@enduml
