@startuml

box "Local components"
    boundary Boundary
    participant Command
    participant SingleMessageProxy as Proxy
    participant SSHConnection
    participant Response
end box

Boundary -> Proxy ++ : Command
Proxy -> SSHConnection ** : Create
Proxy -> SSHConnection ++ : Command
SSHConnection -> Remote ** : Call via shell, YAML as argument
activate Remote
... Remote processes Command, sets environment variable for Response ...
SSHConnection <- Remote -- : Return
destroy Remote
SSHConnection -> SSHConnection: Read environment variable
SSHConnection -> Response ** : Create
Proxy <- SSHConnection -- : Response
Proxy -> SSHConnection !!
Boundary <- Proxy -- : Response

destroy Response

@enduml
