@startuml

participant Proxy

box "Local components"
    participant Remote
    participant MessageHandler
    participant YAMLReader
    participant Command
    participant Response
end box

Proxy -> Remote ** : Call via shell, YAML as argument
activate Remote
Remote --> MessageHandler ++ : Send Command as YAML via socket
Remote -> Remote : Listen for response on socket
MessageHandler -> YAMLReader ++ : Command as YAML
YAMLReader -> Command ** : Create
MessageHandler <- YAMLReader -- : Command
MessageHandler -> MessageHandler : Execute command
MessageHandler -> Response ** : Create
MessageHandler --> Remote : Send Response as YAML via socket
destroy Command
destroy Response
MessageHandler -> MessageHandler : Listen for more Messages
deactivate MessageHandler
Remote -> Remote : Set environment variable \n with Response YAML string
Proxy <- Remote -- : Return
destroy Remote
@enduml
