@startuml

participant Proxy

box "Local components"
    participant Remote
    participant CommandHandler
    participant YAMLReader
    participant Command
    participant Response
end box

Proxy -> Remote ** : Call via shell, YAML as argument
activate Remote
Remote --> CommandHandler ++ : Send Command as YAML via socket
Remote -> Remote : Listen for response on socket
CommandHandler -> YAMLReader ++ : Command as YAML
YAMLReader -> Command ** : Create
CommandHandler <- YAMLReader -- : Command
CommandHandler -> CommandHandler : Execute command
CommandHandler -> Response ** : Create
CommandHandler --> Remote : Send Response as YAML via socket
destroy Command
destroy Response
CommandHandler -> CommandHandler : Listen for more Messages
deactivate CommandHandler
Remote -> Remote : Set environment variable \n with Response YAML string
Proxy <- Remote -- : Return
destroy Remote
@enduml
